# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FKDownloaderDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FKDownloaderDemo
  pod 'FKDownloader', :path => '../'
  pod 'Masonry'
  pod 'MBProgressHUD'

end
